// <auto-generated />
using System;
using API.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(CookBookContext))]
    [Migration("20220516132455_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Bosnian_Latin_100_BIN")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("AppUserId");

                    b.ToTable("AppUser");

                    b.HasData(
                        new
                        {
                            AppUserId = 1,
                            FirstName = "Hanna",
                            LastName = "Tiro",
                            PasswordHash = "JXrkcmVp44bGr/UHHaMyecKVHtY=",
                            PasswordSalt = "RiiHQ3XGHctnPOb7/bxDzQ==",
                            Username = "hanna"
                        },
                        new
                        {
                            AppUserId = 2,
                            FirstName = "Belma",
                            LastName = "Nukic",
                            PasswordHash = "SE2RJHcDP9iTB1Qp5Z+8bddBPLk=",
                            PasswordSalt = "sLspPZEVL0HbIHL6/WCqmA==",
                            Username = "belma"
                        });
                });

            modelBuilder.Entity("API.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Pancakes"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Waffles"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Pizzas"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Fish"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Sushi"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Sandwiches"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Meat"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Pasta"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Asian food"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Taccos"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Barbeque"
                        });
                });

            modelBuilder.Entity("API.Entities.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("IngredientPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Measure")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredient");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            Amount = 9,
                            IngredientName = "Eggs",
                            IngredientPrice = 5m,
                            Measure = "kom"
                        },
                        new
                        {
                            IngredientId = 2,
                            Amount = 170,
                            IngredientName = "Milk",
                            IngredientPrice = 200m,
                            Measure = "l"
                        },
                        new
                        {
                            IngredientId = 3,
                            Amount = 50,
                            IngredientName = "Flour",
                            IngredientPrice = 70m,
                            Measure = "kg"
                        },
                        new
                        {
                            IngredientId = 4,
                            Amount = 2,
                            IngredientName = "Chicken",
                            IngredientPrice = 16m,
                            Measure = "kg"
                        },
                        new
                        {
                            IngredientId = 5,
                            Amount = 2,
                            IngredientName = "Beef",
                            IngredientPrice = 20m,
                            Measure = "kg"
                        },
                        new
                        {
                            IngredientId = 6,
                            Amount = 5,
                            IngredientName = "Cheese",
                            IngredientPrice = 20m,
                            Measure = "kg"
                        },
                        new
                        {
                            IngredientId = 7,
                            Amount = 3,
                            IngredientName = "Yogurt",
                            IngredientPrice = 7m,
                            Measure = "l"
                        },
                        new
                        {
                            IngredientId = 8,
                            Amount = 10,
                            IngredientName = "Patatoes",
                            IngredientPrice = 30m,
                            Measure = "kg"
                        },
                        new
                        {
                            IngredientId = 9,
                            Amount = 10,
                            IngredientName = "Spinach",
                            IngredientPrice = 10m,
                            Measure = "kg"
                        },
                        new
                        {
                            IngredientId = 10,
                            Amount = 17,
                            IngredientName = "Salt",
                            IngredientPrice = 10m,
                            Measure = "kg"
                        },
                        new
                        {
                            IngredientId = 11,
                            Amount = 20,
                            IngredientName = "Peper",
                            IngredientPrice = 10m,
                            Measure = "kg"
                        });
                });

            modelBuilder.Entity("API.Entities.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RecipeId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Recipe");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            CategoryId = 1,
                            Description = "The process is simple!....",
                            RecipeName = "Nutella pancakes",
                            TotalPrice = 5m
                        },
                        new
                        {
                            RecipeId = 2,
                            CategoryId = 1,
                            Description = "The process is simple! ...",
                            RecipeName = "Protein pancakes",
                            TotalPrice = 6m
                        },
                        new
                        {
                            RecipeId = 3,
                            CategoryId = 1,
                            Description = "The process is simple!.....",
                            RecipeName = "Rafaelo pancakes",
                            TotalPrice = 7m
                        });
                });

            modelBuilder.Entity("API.Entities.RecipeDetail", b =>
                {
                    b.Property<int>("RecipeDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("RecipeDetailId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeDetail");

                    b.HasData(
                        new
                        {
                            RecipeDetailId = 1,
                            Amount = 3,
                            IngredientId = 1,
                            Measure = "kom",
                            Price = 1m,
                            RecipeId = 1
                        },
                        new
                        {
                            RecipeDetailId = 2,
                            Amount = 3,
                            IngredientId = 2,
                            Measure = "l",
                            Price = 1m,
                            RecipeId = 1
                        },
                        new
                        {
                            RecipeDetailId = 3,
                            Amount = 20,
                            IngredientId = 3,
                            Measure = "g",
                            Price = 1m,
                            RecipeId = 1
                        },
                        new
                        {
                            RecipeDetailId = 4,
                            Amount = 3,
                            IngredientId = 1,
                            Measure = "kom",
                            Price = 1m,
                            RecipeId = 2
                        },
                        new
                        {
                            RecipeDetailId = 5,
                            Amount = 3,
                            IngredientId = 2,
                            Measure = "l",
                            Price = 1m,
                            RecipeId = 2
                        },
                        new
                        {
                            RecipeDetailId = 6,
                            Amount = 20,
                            IngredientId = 3,
                            Measure = "g",
                            Price = 1m,
                            RecipeId = 2
                        });
                });

            modelBuilder.Entity("API.Entities.Recipe", b =>
                {
                    b.HasOne("API.Entities.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("API.Entities.RecipeDetail", b =>
                {
                    b.HasOne("API.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeDetails")
                        .HasForeignKey("IngredientId")
                        .HasConstraintName("fk_rd_ingr")
                        .IsRequired();

                    b.HasOne("API.Entities.Recipe", "Recipe")
                        .WithMany("RecipeDetails")
                        .HasForeignKey("RecipeId")
                        .HasConstraintName("fk_rd_recep")
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("API.Entities.Category", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("API.Entities.Ingredient", b =>
                {
                    b.Navigation("RecipeDetails");
                });

            modelBuilder.Entity("API.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
