// <auto-generated />
using System;
using CookBook.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CookBook.Database.Migrations
{
    [DbContext(typeof(CookBookContext))]
    [Migration("20220616080556_datab")]
    partial class datab
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Bosnian_Latin_100_BIN")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CookBook.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 977, DateTimeKind.Local).AddTicks(6834),
                            Name = "Pancakes"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(7419),
                            Name = "Waffles"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(7909),
                            Name = "Pizzas"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(7983),
                            Name = "Fish"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8027),
                            Name = "Sushi"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8082),
                            Name = "Sandwiches"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8123),
                            Name = "Meat"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8163),
                            Name = "Pasta"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8200),
                            Name = "Asian food"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8240),
                            Name = "Taccos"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8277),
                            Name = "Barbeque"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8314),
                            Name = "Rice"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8350),
                            Name = "Tortilas"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8386),
                            Name = "Nachos"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8422),
                            Name = "Cakes"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8587),
                            Name = "Jams"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8632),
                            Name = "Omlets"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8670),
                            Name = "Beans"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8703),
                            Name = "Cereal"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8736),
                            Name = "Beef"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8772),
                            Name = "Bread"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8806),
                            Name = "Garlic bread"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8843),
                            Name = "Cabbage"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8876),
                            Name = "Mushrooms"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8910),
                            Name = "Schnitzel"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8944),
                            Name = "Appetiser platter"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(8976),
                            Name = "Vegetarian rice"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(9008),
                            Name = "Vegetarian tortilas"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(9041),
                            Name = "Vegetarian sushi"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(9072),
                            Name = "Vegan sushi"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(9104),
                            Name = "Vegan platter"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(9136),
                            Name = "Vegan pasta"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(9168),
                            Name = "Vegan sandwiches"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 985, DateTimeKind.Local).AddTicks(9281),
                            Name = "Vegan cakes"
                        });
                });

            modelBuilder.Entity("CookBook.Core.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PurchaseAmount")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseMeasure")
                        .HasColumnType("int");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Ingredient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4371),
                            Name = "Eggs",
                            PurchaseAmount = 9,
                            PurchaseMeasure = 4,
                            PurchasePrice = 5m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4415),
                            Name = "Milk",
                            PurchaseAmount = 170,
                            PurchaseMeasure = 2,
                            PurchasePrice = 200m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4423),
                            Name = "Flour",
                            PurchaseAmount = 50,
                            PurchaseMeasure = 0,
                            PurchasePrice = 70m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4430),
                            Name = "Chicken",
                            PurchaseAmount = 2,
                            PurchaseMeasure = 4,
                            PurchasePrice = 16m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4436),
                            Name = "Beef",
                            PurchaseAmount = 2,
                            PurchaseMeasure = 0,
                            PurchasePrice = 20m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4443),
                            Name = "Cheese",
                            PurchaseAmount = 5,
                            PurchaseMeasure = 0,
                            PurchasePrice = 20m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4449),
                            Name = "Yogurt",
                            PurchaseAmount = 3,
                            PurchaseMeasure = 2,
                            PurchasePrice = 7m
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4457),
                            Name = "Patatoes",
                            PurchaseAmount = 10,
                            PurchaseMeasure = 0,
                            PurchasePrice = 30m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4463),
                            Name = "Spinach",
                            PurchaseAmount = 10,
                            PurchaseMeasure = 0,
                            PurchasePrice = 10m
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4470),
                            Name = "Salt",
                            PurchaseAmount = 17,
                            PurchaseMeasure = 0,
                            PurchasePrice = 10m
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4476),
                            Name = "Peper",
                            PurchaseAmount = 20,
                            PurchaseMeasure = 0,
                            PurchasePrice = 10m
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4482),
                            Name = "Snake beans",
                            PurchaseAmount = 20,
                            PurchaseMeasure = 0,
                            PurchasePrice = 10m
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4489),
                            Name = "Cherry tomatoes",
                            PurchaseAmount = 20,
                            PurchaseMeasure = 0,
                            PurchasePrice = 10m
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4496),
                            Name = "Lime",
                            PurchaseAmount = 20,
                            PurchaseMeasure = 0,
                            PurchasePrice = 10m
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4502),
                            Name = "Turnip",
                            PurchaseAmount = 20,
                            PurchaseMeasure = 0,
                            PurchasePrice = 10m
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4508),
                            Name = "Sweet patatoes",
                            PurchaseAmount = 20,
                            PurchaseMeasure = 0,
                            PurchasePrice = 10m
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4515),
                            Name = "Onion",
                            PurchaseAmount = 20,
                            PurchaseMeasure = 0,
                            PurchasePrice = 10m
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4522),
                            Name = "Mushroom",
                            PurchaseAmount = 20,
                            PurchaseMeasure = 0,
                            PurchasePrice = 10m
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4531),
                            Name = "Oregano",
                            PurchaseAmount = 20,
                            PurchaseMeasure = 0,
                            PurchasePrice = 10m
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4538),
                            Name = "Red chilli",
                            PurchaseAmount = 20,
                            PurchaseMeasure = 0,
                            PurchasePrice = 10m
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4544),
                            Name = "Turmeric",
                            PurchaseAmount = 20,
                            PurchaseMeasure = 0,
                            PurchasePrice = 10m
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4551),
                            Name = "Dill",
                            PurchaseAmount = 20,
                            PurchaseMeasure = 0,
                            PurchasePrice = 10m
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4557),
                            Name = "Keema",
                            PurchaseAmount = 20,
                            PurchaseMeasure = 0,
                            PurchasePrice = 10m
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4564),
                            Name = "Crab",
                            PurchaseAmount = 20,
                            PurchaseMeasure = 0,
                            PurchasePrice = 10m
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4571),
                            Name = "Chops",
                            PurchaseAmount = 20,
                            PurchaseMeasure = 0,
                            PurchasePrice = 10m
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4577),
                            Name = "Cranberry",
                            PurchaseAmount = 20,
                            PurchaseMeasure = 0,
                            PurchasePrice = 10m
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4584),
                            Name = "Kiwi",
                            PurchaseAmount = 20,
                            PurchaseMeasure = 0,
                            PurchasePrice = 10m
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4590),
                            Name = "Mango",
                            PurchaseAmount = 20,
                            PurchaseMeasure = 0,
                            PurchasePrice = 10m
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4597),
                            Name = "Watermelon",
                            PurchaseAmount = 20,
                            PurchaseMeasure = 0,
                            PurchasePrice = 10m
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(4603),
                            Name = "Olives",
                            PurchaseAmount = 20,
                            PurchaseMeasure = 0,
                            PurchasePrice = 10m
                        });
                });

            modelBuilder.Entity("CookBook.Core.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Recipe");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(9303),
                            Description = "The process is simple!....",
                            Name = "Nutella pancakes",
                            TotalPrice = 5m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(9351),
                            Description = "The process is simple! ...",
                            Name = "Protein pancakes",
                            TotalPrice = 6m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(9359),
                            Description = "The process is simple!.....",
                            Name = "Rafaelo pancakes",
                            TotalPrice = 7m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(9367),
                            Description = "The process is simple!....",
                            Name = "Neapolitan Pizza",
                            TotalPrice = 5m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(9373),
                            Description = "The process is simple!....",
                            Name = "Sicilian pizza",
                            TotalPrice = 6m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(9379),
                            Description = "The process is simple!....",
                            Name = "Chicago pizza",
                            TotalPrice = 6m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(9496),
                            Description = "The process is simple!....",
                            Name = "California pizza",
                            TotalPrice = 6m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(9506),
                            Description = "The process is simple!....",
                            Name = "Detroit pizza ",
                            TotalPrice = 16m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(9513),
                            Description = "The process is simple!....",
                            Name = "Cheese pasta",
                            TotalPrice = 6m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(9519),
                            Description = "The process is simple!....",
                            Name = "Patato gnocchi",
                            TotalPrice = 6m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(9525),
                            Description = "The process is simple!....",
                            Name = "Linguine",
                            TotalPrice = 6m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(9535),
                            Description = "The process is simple!....",
                            Name = "Bucatini",
                            TotalPrice = 6m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(9541),
                            Description = "The process is simple!....",
                            Name = "Tagliatelle",
                            TotalPrice = 6m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(9547),
                            Description = "The process is simple!....",
                            Name = "Belgian waffles",
                            TotalPrice = 6m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 986, DateTimeKind.Local).AddTicks(9554),
                            Description = "The process is simple!....",
                            Name = "Chocolate waffles",
                            TotalPrice = 6m
                        });
                });

            modelBuilder.Entity("CookBook.Core.Entities.RecipeDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("Measure")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeDetail");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 3,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3086),
                            IngredientId = 1,
                            Measure = 4,
                            Price = 1m,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 3,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3121),
                            IngredientId = 2,
                            Measure = 2,
                            Price = 1m,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 20,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3129),
                            IngredientId = 3,
                            Measure = 1,
                            Price = 1m,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 3,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3135),
                            IngredientId = 1,
                            Measure = 4,
                            Price = 1m,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 3,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3142),
                            IngredientId = 2,
                            Measure = 2,
                            Price = 1m,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Amount = 20,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3148),
                            IngredientId = 3,
                            Measure = 1,
                            Price = 1m,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Amount = 20,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3155),
                            IngredientId = 1,
                            Measure = 1,
                            Price = 1m,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = 10,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3161),
                            IngredientId = 4,
                            Measure = 1,
                            Price = 1m,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 9,
                            Amount = 10,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3167),
                            IngredientId = 4,
                            Measure = 1,
                            Price = 1m,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 10,
                            Amount = 10,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3173),
                            IngredientId = 5,
                            Measure = 1,
                            Price = 1m,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 11,
                            Amount = 10,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3179),
                            IngredientId = 6,
                            Measure = 1,
                            Price = 1m,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 12,
                            Amount = 10,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3186),
                            IngredientId = 2,
                            Measure = 1,
                            Price = 1m,
                            RecipeId = 5
                        },
                        new
                        {
                            Id = 13,
                            Amount = 10,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3192),
                            IngredientId = 6,
                            Measure = 1,
                            Price = 1m,
                            RecipeId = 6
                        },
                        new
                        {
                            Id = 14,
                            Amount = 10,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3198),
                            IngredientId = 3,
                            Measure = 1,
                            Price = 1m,
                            RecipeId = 7
                        },
                        new
                        {
                            Id = 15,
                            Amount = 3,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3204),
                            IngredientId = 4,
                            Measure = 1,
                            Price = 1m,
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 16,
                            Amount = 10,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3210),
                            IngredientId = 7,
                            Measure = 1,
                            Price = 1m,
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 17,
                            Amount = 10,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3216),
                            IngredientId = 5,
                            Measure = 1,
                            Price = 1m,
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 18,
                            Amount = 10,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3222),
                            IngredientId = 8,
                            Measure = 1,
                            Price = 1m,
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 19,
                            Amount = 10,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3229),
                            IngredientId = 9,
                            Measure = 1,
                            Price = 1m,
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 20,
                            Amount = 10,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3235),
                            IngredientId = 10,
                            Measure = 1,
                            Price = 1m,
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 21,
                            Amount = 10,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3241),
                            IngredientId = 11,
                            Measure = 1,
                            Price = 1m,
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 22,
                            Amount = 10,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3247),
                            IngredientId = 15,
                            Measure = 1,
                            Price = 1m,
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 23,
                            Amount = 10,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3254),
                            IngredientId = 17,
                            Measure = 1,
                            Price = 1m,
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 24,
                            Amount = 10,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3260),
                            IngredientId = 18,
                            Measure = 1,
                            Price = 1m,
                            RecipeId = 8
                        },
                        new
                        {
                            Id = 25,
                            Amount = 10,
                            CreatedAt = new DateTime(2022, 6, 16, 10, 5, 54, 987, DateTimeKind.Local).AddTicks(3266),
                            IngredientId = 19,
                            Measure = 1,
                            Price = 1m,
                            RecipeId = 8
                        });
                });

            modelBuilder.Entity("CookBook.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("CookBook.Core.Entities.Recipe", b =>
                {
                    b.HasOne("CookBook.Core.Entities.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CookBook.Core.Entities.RecipeDetail", b =>
                {
                    b.HasOne("CookBook.Core.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .HasConstraintName("fk_rd_ingr")
                        .IsRequired();

                    b.HasOne("CookBook.Core.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .HasConstraintName("fk_rd_recep")
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CookBook.Core.Entities.Category", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("CookBook.Core.Entities.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("CookBook.Core.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
